CREATE EXTERNAL TABLE `inep_json`(
  `co_ano` int, 
  `co_ies` int, 
  `no_ies` string, 
  `org` int, 
  `nomeorg` string, 
  `corede` int, 
  `rede` string, 
  `co_dep` int, 
  `depadm` string, 
  `dep5` int, 
  `regies` int, 
  `regiaoies` string, 
  `coufies` int, 
  `nomeufies` string, 
  `municipioies` string, 
  `comunicies12` bigint, 
  `localies` string, 
  `co_curso` int, 
  `no_curso` string, 
  `reg` int, 
  `no_regiao` string, 
  `couf` int, 
  `no_uf` string, 
  `comunicipio12` bigint, 
  `municipio` string, 
  `local` string, 
  `areageral` int, 
  `noareageral` string, 
  `areaespecifica` int, 
  `noareaespecifica` string, 
  `areadetalhada` int, 
  `noareadetalhada` string, 
  `co_ocde` string, 
  `no_ocde` string, 
  `classe` string, 
  `grau_academico` string, 
  `no_nivel` string, 
  `ncurso` int, 
  `matt` int, 
  `conclt` int, 
  `vagt` int, 
  `inscrt` int, 
  `ingr` int, 
  `ingrps` int, 
  `ingrof` int, 
  `mattranc` int, 
  `matdesvinculada` int, 
  `mattransferido` int, 
  `matfalecido` int)
ROW FORMAT SERDE 
  'org.apache.hive.hcatalog.data.JsonSerDe' 
WITH SERDEPROPERTIES ( 
  'path'='s3://eedb-006-2024-2-grupo-2/benchmark/eedb_006/inep_json') 
LOCATION
  's3://eedb-006-2024-2-grupo-2/benchmark/eedb_006/inep_json'
TBLPROPERTIES (
  'spark.sql.create.version'='3.2.1-amzn-0', 
  'spark.sql.sources.provider'='json', 
  'spark.sql.sources.schema'='{\"type\":\"struct\",\"fields\":[{\"name\":\"CO_ANO\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CO_IES\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_IES\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"ORG\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NOMEORG\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"COREDE\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"rede\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CO_DEP\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"DEPADM\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dep5\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"REGIES\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"REGIAOIES\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"COUFIES\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NOMEUFIES\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MUNICIPIOIES\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"COMUNICIES12\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}},{\"name\":\"LOCALIES\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CO_CURSO\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_CURSO\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"REG\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_REGIAO\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"COUF\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_UF\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"COMUNICIPIO12\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}},{\"name\":\"municipio\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"LOCAL\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"AREAGERAL\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NOAREAGERAL\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"AREAESPECIFICA\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NOAREAESPECIFICA\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"AREADETALHADA\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NOAREADETALHADA\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CO_OCDE\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_OCDE\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CLASSE\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"GRAU_ACADEMICO\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NO_NIVEL\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"NCURSO\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MATT\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"CONCLT\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"VAGT\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"INSCRT\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"INGR\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"INGRPS\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"INGROF\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MATTRANC\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MATDESVINCULADA\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MATTRANSFERIDO\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"MATFALECIDO\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}]}', 
  'transient_lastDdlTime'='1721086014')